-- MySQL Script generated by MySQL Workbench
-- Sun 13 Nov 2016 11:34:09 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mkubis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mkubis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkubis` DEFAULT CHARACTER SET utf8 ;
USE `mkubis` ;

-- -----------------------------------------------------
-- Table `mkubis`.`pokemons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`pokemons` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`pokemons` (
  `pokemon_name` VARCHAR(50) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `cp` INT UNSIGNED NOT NULL,
  `hp` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pokemon_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`teams` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`teams` (
  `team_name` VARCHAR(50) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`team_name`),
  UNIQUE INDEX `color_UNIQUE` (`color` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`trainers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`trainers` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`trainers` (
  `trainer_name` VARCHAR(50) NOT NULL,
  `team_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`trainer_name`),
  INDEX `fk_trainers_teams1_idx` (`team_name` ASC),
  CONSTRAINT `fk_trainers_teams1`
    FOREIGN KEY (`team_name`)
    REFERENCES `mkubis`.`teams` (`team_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`cities` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`cities` (
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`city_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`gyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`gyms` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`gyms` (
  `num` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `badge` VARCHAR(45) NOT NULL,
  `leader_name` VARCHAR(50) NOT NULL,
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`num`, `city_name`),
  INDEX `fk_gyms_cities1_idx` (`city_name` ASC),
  INDEX `fk_gyms_trainers1_idx` (`leader_name` ASC),
  CONSTRAINT `fk_gyms_cities1`
    FOREIGN KEY (`city_name`)
    REFERENCES `mkubis`.`cities` (`city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gyms_trainers1`
    FOREIGN KEY (`leader_name`)
    REFERENCES `mkubis`.`trainers` (`trainer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`stores` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`stores` (
  `loc` VARCHAR(50) NOT NULL,
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`loc`, `city_name`),
  INDEX `fk_stores_cities1_idx` (`city_name` ASC),
  CONSTRAINT `fk_stores_cities1`
    FOREIGN KEY (`city_name`)
    REFERENCES `mkubis`.`cities` (`city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`items` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`items` (
  `item_name` VARCHAR(50) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`item_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`healing_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`healing_items` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`healing_items` (
  `item_name` VARCHAR(50) NOT NULL,
  `amount_healed` INT NOT NULL,
  PRIMARY KEY (`item_name`),
  CONSTRAINT `fk_healing_items_items`
    FOREIGN KEY (`item_name`)
    REFERENCES `mkubis`.`items` (`item_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`combat_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`combat_items` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`combat_items` (
  `item_name` VARCHAR(50) NOT NULL,
  `cp` INT NOT NULL,
  PRIMARY KEY (`item_name`),
  CONSTRAINT `fk_combat_items_items1`
    FOREIGN KEY (`item_name`)
    REFERENCES `mkubis`.`items` (`item_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`pokeballs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`pokeballs` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`pokeballs` (
  `item_name` VARCHAR(50) NOT NULL,
  `catch_rate` DOUBLE NOT NULL,
  PRIMARY KEY (`item_name`),
  CONSTRAINT `fk_pokeballs_items1`
    FOREIGN KEY (`item_name`)
    REFERENCES `mkubis`.`items` (`item_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`pokemons_trainers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`pokemons_trainers` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`pokemons_trainers` (
  `pokemon_name` VARCHAR(50) NOT NULL,
  `trainer_name` VARCHAR(50) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`pokemon_name`, `trainer_name`, `date`),
  INDEX `fk_pokemons_has_trainers_trainers1_idx` (`trainer_name` ASC),
  INDEX `fk_pokemons_has_trainers_pokemons1_idx` (`pokemon_name` ASC),
  CONSTRAINT `fk_pokemons_has_trainers_pokemons1`
    FOREIGN KEY (`pokemon_name`)
    REFERENCES `mkubis`.`pokemons` (`pokemon_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemons_has_trainers_trainers1`
    FOREIGN KEY (`trainer_name`)
    REFERENCES `mkubis`.`trainers` (`trainer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`members` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`members` (
  `gym_num` INT UNSIGNED NOT NULL,
  `trainer_name` VARCHAR(50) NOT NULL,
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`gym_num`, `trainer_name`, `city_name`),
  INDEX `fk_trainers_has_gyms_gyms1_idx` (`gym_num` ASC, `city_name` ASC),
  INDEX `fk_trainers_has_gyms_trainers1_idx` (`trainer_name` ASC),
  CONSTRAINT `fk_trainers_has_gyms_trainers1`
    FOREIGN KEY (`trainer_name`)
    REFERENCES `mkubis`.`trainers` (`trainer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainers_has_gyms_gyms1`
    FOREIGN KEY (`gym_num` , `city_name`)
    REFERENCES `mkubis`.`gyms` (`num` , `city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkubis`.`stores_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mkubis`.`stores_items` ;

CREATE TABLE IF NOT EXISTS `mkubis`.`stores_items` (
  `item_name` VARCHAR(50) NOT NULL,
  `loc` VARCHAR(50) NOT NULL,
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`item_name`, `loc`, `city_name`),
  INDEX `fk_stores_has_items_items1_idx` (`item_name` ASC),
  INDEX `fk_stores_has_items_stores1_idx` (`loc` ASC, `city_name` ASC),
  CONSTRAINT `fk_stores_has_items_stores1`
    FOREIGN KEY (`loc` , `city_name`)
    REFERENCES `mkubis`.`stores` (`loc` , `city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stores_has_items_items1`
    FOREIGN KEY (`item_name`)
    REFERENCES `mkubis`.`items` (`item_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
