insert into stores(city_name,loc) values ('Stony River','Indiana');
insert into stores(city_name,loc)  values ('Sugarloaf','Rio de Janeiro');
insert into stores(city_name,loc) values ('Summit Hill','Dallas');
insert into stores(city_name,loc)  values ('Sunrise Beach','Missouri');
insert into stores(city_name,loc) values ('Waldwick','New Jersey');
insert into stores(city_name,loc) values ('Abilene','Brooklyn');
insert into stores(city_name,loc)  values ('Alamo','New York');
insert into stores(city_name,loc) values ('Cedartown','Georgia');
insert into stores(city_name,loc) values ('Cherry','Alabama');
insert into stores(city_name,loc) values ('Harrison','Virginia');
insert into stores(city_name,loc)  values ('Keeneland','Kentucky');
insert into stores(city_name,loc) values ('Key West','Florida');
insert into stores(city_name,loc) values ('Kinsey','Texas');
insert into stores(city_name,loc)  values ('Norbeck','Washington');
insert into stores(city_name,loc) values ('North Albany','New Jersey');
insert into stores(city_name,loc) values ('Northfork','West Virginia');
insert into stores(city_name,loc) values ('Oakford','Baltimore');
insert into stores(city_name,loc) values ('Octavia','San Francisco');
insert into stores(city_name,loc) values ('Pageland','South Carolina');
insert into stores(city_name,loc) values ('Palm City','Florida');
insert into stores(city_name,loc) values ('Panama City','Florida');
insert into stores(city_name,loc) values ('Peabody','Massachusetts');
insert into stores(city_name,loc) values ('Raymond','New Hampshire');
insert into stores(city_name,loc) values ('Reddick','Illinois');
insert into stores(city_name,loc) values ('Sanchez','Chicago');
insert into stores(city_name,loc) values ('Shallow Water','Indiana');
insert into stores(city_name,loc) values ('Sparta','Tennessee');
insert into stores(city_name,loc) values ('Tundra','Missouri');
insert into stores(city_name,loc) values ('Udall','Kansas');
insert into stores(city_name,loc) values ('Uncasville','Connecticut');
insert into stores(city_name,loc) values ('Tulalip Bay','Washington');
insert into stores(city_name,loc)  values ('Valley View','Washington');
insert into stores(city_name,loc) values ('Violet Hill','California');
insert into stores(city_name,loc) values ('Wading River','New York');
insert into stores(city_name,loc)  values ('Waldorf','Maryland');
insert into stores(city_name,loc) values ('West Forks','Arizona');
insert into stores(city_name,loc) values ('Yardley','Pennsylvania');
insert into stores(city_name,loc) values ('Zelienople','Pennsylvania');
insert into stores(city_name,loc) values ('Zolfo Springs','Florida');
insert into stores(city_name,loc) values ('Adel','Georgia');
insert into stores(city_name,loc)  values ('Arizona City','Arizona');
insert into stores(city_name,loc) values ('Atlantic City','New Jersey');
insert into stores(city_name,loc) values ('Dime Box','Texas');
insert into stores(city_name,loc) values ('Dunwoody','Georgia');
insert into stores(city_name,loc) values ('Francis Mills','New Jersey');
insert into stores(city_name,loc)  values ('Gas City','Indiana');
insert into stores(city_name,loc) values ('German Valley','Illinois');
insert into stores(city_name,loc) values ('Hahira','Georgia');
insert into stores(city_name,loc) values ('Hamilton City','Ohio');
insert into stores(city_name,loc)  values ('Hendrum','Minnesota');
insert into stores(city_name,loc)  values ('Imperial Beach','California');
insert into stores(city_name,loc) values ('Indianapolis','Indiana');
insert into stores(city_name,loc) values ('Jacksboro','Texas');
insert into stores(city_name,loc) values ('Kansas City','Kansas');
insert into stores(city_name,loc) values ('Kettle River','Wyoming');
insert into stores(city_name,loc) values ('Labouchere Bay','Canada');
insert into stores(city_name,loc) values ('Ladera Heights','California');
insert into stores(city_name,loc) values ('Lane City','Oregon');
insert into stores(city_name,loc)  values ('Las Vegas','Nevada');
insert into stores(city_name,loc)  values ('Manassas Park','Virginia');
insert into stores(city_name,loc) values ('Marvell','Arkansas');
insert into stores(city_name,loc) values ('Milwaukee','Wisconsin');
insert into stores(city_name,loc) values ('Nelagoney','Oklahoma');
insert into stores(city_name,loc) values ('Gulf Crest','Texas');
insert into stores(city_name,loc) values ('Frackville','Pennsylvania');
insert into stores(city_name,loc) values ('New Chicago','Indiana');
insert into stores(city_name,loc) values ('Pilsen','Chicago');
insert into stores(city_name,loc)  values ('Lathrup Village','Michigan');
insert into stores(city_name,loc) values ('Lake Wisconsin','Wisconsin');
insert into stores(city_name,loc) values ('Iowa','Iowa');
insert into stores(city_name,loc) values ('Ipswich','Massachusetts');
insert into stores(city_name,loc) values ('Quincy','Massachusetts');
insert into stores(city_name,loc) values ('Railroad','Massachusetts');
insert into stores(city_name,loc) values ('Rainbow City','Alabama');
insert into stores(city_name,loc) values ('River Rouge','Tennessee');
insert into stores(city_name,loc) values ('Saint Elmo','Illinois');
insert into stores(city_name,loc) values ('Sofia','Louisiana');
insert into stores(city_name,loc)  values ('Tampa','Florida');
insert into stores(city_name,loc) values ('Thunderbolt','Georgia');
insert into stores(city_name,loc) values ('Topeka','Kansas');
insert into stores(city_name,loc) values ('Universal City','California');
insert into stores(city_name,loc) values ('Virgin','California');
insert into stores(city_name,loc) values ('Wahoo','California');
insert into stores(city_name,loc) values ('West Sunbury','Pennsylvania');
insert into stores(city_name,loc) values ('White Tower','Virginia');
insert into stores(city_name,loc)  values ('Y City','Arkansas');
insert into stores(city_name,loc) values ('Zapata','Texas');
insert into stores(city_name,loc) values ('Amorita','Oklahoma');
insert into stores(city_name,loc)  values ('Apache Junction','Arizona');
insert into stores(city_name,loc) values ('Decatur','Alabama');
insert into stores(city_name,loc) values ('Fort Ripley','Minnesota');
insert into stores(city_name,loc)  values ('Fountain Hill','Iowa');
insert into stores(city_name,loc) values ('Garden Acres','Texas');
insert into stores(city_name,loc)  values ('Glenmoor','Maryland');
insert into stores(city_name,loc) values ('Gran Quivira','New Mexico');
insert into stores(city_name,loc) values ('Grandfield','Louisiana');
insert into stores(city_name,loc)  values ('Hamorton','South Carolina');
insert into stores(city_name,loc) values ('Jasmine Estates','Florida');
insert into stores(city_name,loc) values ('Kachemak City','Alaska');
insert into stores(city_name,loc) values ('Las Animas','Colorado');


