INSERT INTO healing_items(item_name, amount_healed) values('Max Potion', 750);
INSERT INTO healing_items(item_name, amount_healed) values('Max Elixir', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Max Revive', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Max Revive', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Rage Candy Bar', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Revival Herb', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Sacred Ash', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Sweet Heart', 300);
INSERT INTO healing_items(item_name, amount_healed) values('Green Candycane', 250);
INSERT INTO healing_items(item_name, amount_healed) values('Halloween Candy', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Pumpkin', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Revive', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Hyper Potion', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Red Candycane', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Lumiose Galette', 150);
INSERT INTO healing_items(item_name, amount_healed) values('Secret Potion', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Elixir', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Ether', 200);
INSERT INTO healing_items(item_name, amount_healed) values('Old Gateau', 100);
INSERT INTO healing_items(item_name, amount_healed) values('Casteliacone', 100);
INSERT INTO healing_items(item_name, amount_healed) values('Shalour Sable', 100);
INSERT INTO healing_items(item_name, amount_healed) values('Lemonade', 100);
INSERT INTO healing_items(item_name, amount_healed) values('MooMoo Milk', 100);
INSERT INTO healing_items(item_name, amount_healed) values('Lava Cookie', 100);
INSERT INTO healing_items(item_name, amount_healed) values('Soda Pop', 60);
INSERT INTO healing_items(item_name, amount_healed) values('Super Potion', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Awakening', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Burn Heal', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Ice Heal', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Heat Heal', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Frozen Heal', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Full Heal', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Full Restore', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Fresh Water', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Rainbow Candycane', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Cheri Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Chesto Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Pecha Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Rawst Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Aspear Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Leppa Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Oran Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Persim Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Lum Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Sitrus Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Figy Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Wiki Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Mago Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Aguav Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Iapapa Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Razz Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Bluk Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Nanab Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Wepear Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Pinap Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Pomeg Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Kelpsy Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Qualot Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Hondew Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Grepa Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Tamato Berry', 50);
INSERT INTO healing_items(item_name, amount_healed) values('Cornn Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Magost Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Rabuta Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Nomel Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Spelon Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Pamter Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Watmel Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Durin Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Belue Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Occa Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Passho Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Wacan Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Rindo Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Yache Berry', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Potion', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Antidote', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Paralyze Heal', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Berry Juice', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Orange Juice', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Apple Juice', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Melon Juice', 20);
INSERT INTO healing_items(item_name, amount_healed) values('Chocolate Bar', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Chople Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Kebia Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Shuca Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Coba Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Payapa Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Tanga Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Charati Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Kasib Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Haban Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Colbur Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Babiri Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Chilan Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Liechi Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Ganlon Berry', 10);

INSERT INTO healing_items(item_name, amount_healed) values('Salac Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Petaya Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Apicot Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Lansat Berry', 10);
INSERT INTO healing_items(item_name, amount_healed) values('Starf Berry', 10);




