
insert into teams(team_name,color) values('Instinct','Yellow');
insert into teams(team_name,color) values('Mystic','Blue');
insert into teams(team_name,color) values('Valor','Red');
insert into teams(team_name,color) values('Accius','Acid Green');
insert into teams(team_name,color) values('Achaicus','Aero Blue');
insert into teams(team_name,color) values('Acteon','Alloy Orange');
insert into teams(team_name,color) values('Adolphus','Almod');
insert into teams(team_name,color) values('Ajax','Silver');
insert into teams(team_name,color) values('Alcimus','Amber');
insert into teams(team_name,color) values('Benignus','Purple');
insert into teams(team_name,color) values('Bonifatius','Amethyst');
insert into teams(team_name,color) values('Canutus','White');
insert into teams(team_name,color) values('Capaneus','Bronze');
insert into teams(team_name,color) values('Carolus','Aquamarine');
insert into teams(team_name,color) values('Celsus','Arsenic');
insert into teams(team_name,color) values('Deodatus','Azure');
insert into teams(team_name,color) values('Dorus','Bazaar');
insert into teams(team_name,color) values('Duilius','Begonia');
insert into teams(team_name,color) values('Egidius','Beige');
insert into teams(team_name,color) values('Elanius','Black');
insert into teams(team_name,color) values('Eolus','Blizzard Blue');
insert into teams(team_name,color) values('Ether','Green');
insert into teams(team_name,color) values('Felix','Orange');
insert into teams(team_name,color) values('Ferox','Royal Purple');
insert into teams(team_name,color) values('Gabinus','Burgundy');
insert into teams(team_name,color) values('Georgius','Cadet');
insert into teams(team_name,color) values('Gordian','Cadmium Yellow');
insert into teams(team_name,color) values('Helier','Camel');
insert into teams(team_name,color) values('Ianus','Magenta');
insert into teams(team_name,color) values('Iovis','Deep Maroon');
insert into teams(team_name,color) values('Jacomus','Denim');
insert into teams(team_name,color) values('Jericho','Deer');
insert into teams(team_name,color) values('Jove','Diamond');
insert into teams(team_name,color) values('Ladislaus','Dim Gray');
insert into teams(team_name,color) values('Kaius','Dodger Blue');
insert into teams(team_name,color) values('Lazarus','Drab');
insert into teams(team_name,color) values('Leander','Ebony');
insert into teams(team_name,color) values('Lexus','Dutch White');
insert into teams(team_name,color) values('Livius','Electric Blue');
insert into teams(team_name,color) values('Lucan','Emerald');
insert into teams(team_name,color) values('Ludo','Eminence');
insert into teams(team_name,color) values('Lucius','Fallow');
insert into teams(team_name,color) values('Lysander','Eucalyptus');
insert into teams(team_name,color) values('Macarius','Fandango');
insert into teams(team_name,color) values('Magnus','Feldgrau');
insert into teams(team_name,color) values('Manius','Fiery Rose');
insert into teams(team_name,color) values('Maxim','Fawn');
insert into teams(team_name,color) values('Mercury','French Beige');
insert into teams(team_name,color) values('Menelaus','Folly');
insert into teams(team_name,color) values('Naevius','Frostbite');
insert into teams(team_name,color) values('Neleus','Dark Red');
insert into teams(team_name,color) values('Nemo','Dark Taupe');
insert into teams(team_name,color) values('Neptune','Dark Vanilla');
insert into teams(team_name,color) values('Nereus','Deep Cerise');
insert into teams(team_name,color) values('Nero','Deep Mauve');
insert into teams(team_name,color) values('Nicator','Fuchsia');
insert into teams(team_name,color) values('Nigellus','Fulvous');
insert into teams(team_name,color) values('Octavia','Deep Frostbite');
insert into teams(team_name,color) values('Oceanus','Cornell Red');
insert into teams(team_name,color) values('Oeneus','Cornsilk');
insert into teams(team_name,color) values('Olympus','Coral Reef');
insert into teams(team_name,color) values('Orlandus','Cobalt');
insert into teams(team_name,color) values('Pantera','Crimson');
insert into teams(team_name,color) values('Pamphilus','Cyan');
insert into teams(team_name,color) values('Patricius','Daffodil');
insert into teams(team_name,color) values('Petrus','Dandelion');
insert into teams(team_name,color) values('Philetus','Dark Blue');
insert into teams(team_name,color) values('Phocas','Dark Coral');
insert into teams(team_name,color) values('Portunus','Dark Green');
insert into teams(team_name,color) values('Primus','Gunmetal');
insert into teams(team_name,color) values('Priscus','Lava');
insert into teams(team_name,color) values('Proteus','Lavander');
insert into teams(team_name,color) values('Publius','Dark Orchid');
insert into teams(team_name,color) values('Quique','Pastel Blue');
insert into teams(team_name,color) values('Rabanus','Dark Puce');
insert into teams(team_name,color) values('Ramirus','Scarlet');
insert into teams(team_name,color) values('Renatus','Sky Blue');
insert into teams(team_name,color) values('Robertus','Vanilla');
insert into teams(team_name,color) values('Rogerius','Debian Red');
insert into teams(team_name,color) values('Rollo','Deep Carmine');
insert into teams(team_name,color) values('Rufus','Saffron');
insert into teams(team_name,color) values('Sabinus','Deep Taupe');
insert into teams(team_name,color) values('Sandalius','Violet');
insert into teams(team_name,color) values('Secundus','Dark Gray');
insert into teams(team_name,color) values('Sergius','Dollar Bill');
insert into teams(team_name,color) values('Silenus','Donkey Brown');
insert into teams(team_name,color) values('Silvius','Duke Blue');
insert into teams(team_name,color) values('Sophocles','Ecru');
insert into teams(team_name,color) values('Sophus','Eton Blue');
insert into teams(team_name,color) values('Stamatius','Falu Red');
insert into teams(team_name,color) values('Stefanus','Electric Cyan');
insert into teams(team_name,color) values('Tatianus','Dark Black');
insert into teams(team_name,color) values('Terentius','Dark Ebony');
insert into teams(team_name,color) values('Thelonius','Desert Sand');
insert into teams(team_name,color) values('Tiberius','Deep Lilac');
insert into teams(team_name,color) values('Timeus','Turquoise');
insert into teams(team_name,color) values('Urbanus','Deep Lemon');
insert into teams(team_name,color) values('Urias','Orchid');
insert into teams(team_name,color) values('Varinius','Medium Gray');
insert into teams(team_name,color) values('Velius','Khaki');

