INSERT INTO combat_items(item_name, cp) values('X Attack',10);
INSERT INTO combat_items(item_name, cp) values('X Defense', 10);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk',10);
INSERT INTO combat_items(item_name, cp) values('X SP. Def', 10);
INSERT INTO combat_items(item_name, cp) values('X Speed',10);
INSERT INTO combat_items(item_name, cp) values('X Accuracy', 10);
INSERT INTO combat_items(item_name, cp) values('Dire Hit',10);
INSERT INTO combat_items(item_name, cp) values('X Special', 10);
INSERT INTO combat_items(item_name, cp) values('X Attack_2',20);
INSERT INTO combat_items(item_name, cp) values('X Defense_2', 20);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk_2',20);
INSERT INTO combat_items(item_name, cp) values('X SP. Def_2', 20);
INSERT INTO combat_items(item_name, cp) values('X Speed_2',20);
INSERT INTO combat_items(item_name, cp) values('X Accuracy_2', 20);
INSERT INTO combat_items(item_name, cp) values('Dire Hit_2',20);
INSERT INTO combat_items(item_name, cp) values('X Special_2', 20);
INSERT INTO combat_items(item_name, cp) values('X Attack_3',30);
INSERT INTO combat_items(item_name, cp) values('X Defense_3', 30);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk_3',30);
INSERT INTO combat_items(item_name, cp) values('X SP. Def_3', 30);
INSERT INTO combat_items(item_name, cp) values('X Speed_3',30);
INSERT INTO combat_items(item_name, cp) values('X Accuracy_3', 30);
INSERT INTO combat_items(item_name, cp) values('Dire Hit_3',30);
INSERT INTO combat_items(item_name, cp) values('X Special_3', 30);
INSERT INTO combat_items(item_name, cp) values('X Attack_4',40);
INSERT INTO combat_items(item_name, cp) values('X Defense_4', 40);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk_4',40);
INSERT INTO combat_items(item_name, cp) values('X SP. Def_4', 40);
INSERT INTO combat_items(item_name, cp) values('X Speed_4',40);
INSERT INTO combat_items(item_name, cp) values('X Accuracy_4', 40);
INSERT INTO combat_items(item_name, cp) values('Dire Hit_4',40);
INSERT INTO combat_items(item_name, cp) values('X Special_4', 40);
INSERT INTO combat_items(item_name, cp) values('X Attack_5',50);
INSERT INTO combat_items(item_name, cp) values('X Defense_5', 50);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk_5',50);
INSERT INTO combat_items(item_name, cp) values('X SP. Def_5', 50);
INSERT INTO combat_items(item_name, cp) values('X Speed_5',50);
INSERT INTO combat_items(item_name, cp) values('X Accuracy_5', 50);
INSERT INTO combat_items(item_name, cp) values('Dire Hit_5',50);
INSERT INTO combat_items(item_name, cp) values('X Special_5', 50);
INSERT INTO combat_items(item_name, cp) values('X Attack_6',60);
INSERT INTO combat_items(item_name, cp) values('X Defense_6', 60);
INSERT INTO combat_items(item_name, cp) values('X SP. Atk_6',60);
INSERT INTO combat_items(item_name, cp) values('X SP. Def_6', 60);
INSERT INTO combat_items(item_name, cp) values('X Speed_6',60);
INSERT INTO combat_items(item_name, cp) values('X Accuracy_6', 60);
INSERT INTO combat_items(item_name, cp) values('Dire Hit_6',60);
INSERT INTO combat_items(item_name, cp) values('X Special_6', 60);
INSERT INTO combat_items(item_name, cp) values('Guard Spec', 20);
INSERT INTO combat_items(item_name, cp) values('Item Drop', 20);
INSERT INTO combat_items(item_name, cp) values('Item Urge',20);
INSERT INTO combat_items(item_name, cp) values('Absorb Bulb', 20);
INSERT INTO combat_items(item_name, cp) values('Air Balloon', 20);
INSERT INTO combat_items(item_name, cp) values('Assault Vest',20);
INSERT INTO combat_items(item_name, cp) values('Big Root', 20);
INSERT INTO combat_items(item_name, cp) values('Binding Band', 20);
INSERT INTO combat_items(item_name, cp) values('Black Sludge',20);
INSERT INTO combat_items(item_name, cp) values('Reset Urge', 20);
INSERT INTO combat_items(item_name, cp) values('Start Urge',20);
INSERT INTO combat_items(item_name, cp) values('Bright Powder',30);
INSERT INTO combat_items(item_name, cp) values('Cell Battery', 30);
INSERT INTO combat_items(item_name, cp) values('Choice Band',30);
INSERT INTO combat_items(item_name, cp) values('Damp Rock', 30);
INSERT INTO combat_items(item_name, cp) values('Deep Sea Scale',30);
INSERT INTO combat_items(item_name, cp) values('Destiny Knot', 30);
INSERT INTO combat_items(item_name, cp) values('Eject Button',30);
INSERT INTO combat_items(item_name, cp) values('Float Stone', 30);
INSERT INTO combat_items(item_name, cp) values('Flame Orb', 30);
INSERT INTO combat_items(item_name, cp) values('Focus Band',30);
INSERT INTO combat_items(item_name, cp) values('Full Incense', 30);
INSERT INTO combat_items(item_name, cp) values('Grip Claw',40);
INSERT INTO combat_items(item_name, cp) values('Heat Rock', 40);
INSERT INTO combat_items(item_name, cp) values('Icy Rock',40);
INSERT INTO combat_items(item_name, cp) values('Iron Ball', 40);
INSERT INTO combat_items(item_name, cp) values('King Rock',40);
INSERT INTO combat_items(item_name, cp) values('Lucky Egg', 40);
INSERT INTO combat_items(item_name, cp) values('Lucky Punch',40);
INSERT INTO combat_items(item_name, cp) values('Mental Herb', 40);
INSERT INTO combat_items(item_name, cp) values('Metal Powder', 30);
INSERT INTO combat_items(item_name, cp) values('Metronome',30);
INSERT INTO combat_items(item_name, cp) values('Muscle Band', 30);
INSERT INTO combat_items(item_name, cp) values('Power Herb',40);
INSERT INTO combat_items(item_name, cp) values('Wide Lens', 40);
INSERT INTO combat_items(item_name, cp) values('Wise Ball',40);
INSERT INTO combat_items(item_name, cp) values('Zoom Ball', 40);
INSERT INTO combat_items(item_name, cp) values('Sticky Ball',40);
INSERT INTO combat_items(item_name, cp) values('Soothe Ball', 40);
INSERT INTO combat_items(item_name, cp) values('Rocky Ball',40);
INSERT INTO combat_items(item_name, cp) values('Pure Incense', 40);
INSERT INTO combat_items(item_name, cp) values('Quick Powder',40);
INSERT INTO combat_items(item_name, cp) values('Razor Claw', 40);
INSERT INTO combat_items(item_name, cp) values('Razon Fang',40);
INSERT INTO combat_items(item_name, cp) values('Ring Target', 40);
INSERT INTO combat_items(item_name, cp) values('Rocky Helmet',40);
INSERT INTO combat_items(item_name, cp) values('Safety Goggles', 40);
INSERT INTO combat_items(item_name, cp) values('Scope Lens',50);
INSERT INTO combat_items(item_name, cp) values('Shed Shell', 50);
INSERT INTO combat_items(item_name, cp) values('Shell Bell',50);
INSERT INTO combat_items(item_name, cp) values('Smoke Bell', 50);
INSERT INTO combat_items(item_name, cp) values('Smoke Ball',50);
INSERT INTO combat_items(item_name, cp) values('Stick', 50);
INSERT INTO combat_items(item_name, cp) values('Thick Club',50);
INSERT INTO combat_items(item_name, cp) values('Toxic Orb', 50);
INSERT INTO combat_items(item_name, cp) values('Ability Urge',100);
