
-- combat_items

INSERT INTO items(item_name, cp) values('X Attack',250);
INSERT INTO items(item_name, cp) values('X Defense', 250);
INSERT INTO items(item_name, cp) values('X SP. Atk',250);
INSERT INTO items(item_name, cp) values('X SP. Def', 250);
INSERT INTO items(item_name, cp) values('X Speed',250);
INSERT INTO items(item_name, cp) values('X Accuracy', 250);
INSERT INTO items(item_name, cp) values('Dire Hit',250);
INSERT INTO items(item_name, cp) values('X Special', 250);
INSERT INTO items(item_name, cp) values('X Attack_2',275);
INSERT INTO items(item_name, cp) values('X Defense_2', 275);
INSERT INTO items(item_name, cp) values('X SP. Atk_2',275);
INSERT INTO items(item_name, cp) values('X SP. Def_2', 275);
INSERT INTO items(item_name, cp) values('X Speed_2',275);
INSERT INTO items(item_name, cp) values('X Accuracy_2', 275);
INSERT INTO items(item_name, cp) values('Dire Hit_2',275);
INSERT INTO items(item_name, cp) values('X Special_2', 275);
INSERT INTO items(item_name, cp) values('X Attack_3',550);
INSERT INTO items(item_name, cp) values('X Defense_3', 550);
INSERT INTO items(item_name, cp) values('X SP. Atk_3',550);
INSERT INTO items(item_name, cp) values('X SP. Def_3', 550);
INSERT INTO items(item_name, cp) values('X Speed_3',550);
INSERT INTO items(item_name, cp) values('X Accuracy_3', 550);
INSERT INTO items(item_name, cp) values('Dire Hit_3',550);
INSERT INTO items(item_name, cp) values('X Special_3', 550);
INSERT INTO items(item_name, cp) values('X Attack_4',650);
INSERT INTO items(item_name, cp) values('X Defense_4', 650);
INSERT INTO items(item_name, cp) values('X SP. Atk_4',650);
INSERT INTO items(item_name, cp) values('X SP. Def_4', 650);
INSERT INTO items(item_name, cp) values('X Speed_4',650);
INSERT INTO items(item_name, cp) values('X Accuracy_4', 650);
INSERT INTO items(item_name, cp) values('Dire Hit_4',650);
INSERT INTO items(item_name, cp) values('X Special_4', 650);
INSERT INTO items(item_name, cp) values('X Attack_5',7650);
INSERT INTO items(item_name, cp) values('X Defense_5', 750);
INSERT INTO items(item_name, cp) values('X SP. Atk_5',750);
INSERT INTO items(item_name, cp) values('X SP. Def_5', 750);
INSERT INTO items(item_name, cp) values('X Speed_5',750);
INSERT INTO items(item_name, cp) values('X Accuracy_5', 750);
INSERT INTO items(item_name, cp) values('Dire Hit_5',750);
INSERT INTO items(item_name, cp) values('X Special_5', 750);
INSERT INTO items(item_name, cp) values('X Attack_6',500);
INSERT INTO items(item_name, cp) values('X Defense_6', 500);
INSERT INTO items(item_name, cp) values('X SP. Atk_6',500);
INSERT INTO items(item_name, cp) values('X SP. Def_6', 500);
INSERT INTO items(item_name, cp) values('X Speed_6',500);
INSERT INTO items(item_name, cp) values('X Accuracy_6', 500);
INSERT INTO items(item_name, cp) values('Dire Hit_6',500);
INSERT INTO items(item_name, cp) values('X Special_6', 500);
INSERT INTO items(item_name, cp) values('Guard Spec', 275);
INSERT INTO items(item_name, cp) values('Item Drop', 275);
INSERT INTO items(item_name, cp) values('Item Urge',275);
INSERT INTO items(item_name, cp) values('Absorb Bulb', 275);
INSERT INTO items(item_name, cp) values('Air Balloon', 275);
INSERT INTO items(item_name, cp) values('Assault Vest',275);
INSERT INTO items(item_name, cp) values('Big Root', 275);
INSERT INTO items(item_name, cp) values('Binding Band', 275);
INSERT INTO items(item_name, cp) values('Black Sludge',275);
INSERT INTO items(item_name, cp) values('Reset Urge', 275);
INSERT INTO items(item_name, cp) values('Start Urge',275);
INSERT INTO items(item_name, cp) values('Bright Powder',550);
INSERT INTO items(item_name, cp) values('Cell Battery', 550);
INSERT INTO items(item_name, cp) values('Choice Band',550);
INSERT INTO items(item_name, cp) values('Damp Rock', 550);
INSERT INTO items(item_name, cp) values('Deep Sea Scale',550);
INSERT INTO items(item_name, cp) values('Destiny Knot', 550);
INSERT INTO items(item_name, cp) values('Eject Button',550);
INSERT INTO items(item_name, cp) values('Float Stone', 550);
INSERT INTO items(item_name, cp) values('Flame Orb', 550);
INSERT INTO items(item_name, cp) values('Focus Band',550);
INSERT INTO items(item_name, cp) values('Full Incense', 550);
INSERT INTO items(item_name, cp) values('Grip Claw',650);
INSERT INTO items(item_name, cp) values('Heat Rock', 650);
INSERT INTO items(item_name, cp) values('Icy Rock',650);
INSERT INTO items(item_name, cp) values('Iron Ball', 650);
INSERT INTO items(item_name, cp) values('King Rock',650);
INSERT INTO items(item_name, cp) values('Lucky Egg', 650);
INSERT INTO items(item_name, cp) values('Lucky Punch',650);
INSERT INTO items(item_name, cp) values('Mental Herb', 650);
INSERT INTO items(item_name, cp) values('Metal Powder', 550);
INSERT INTO items(item_name, cp) values('Metronome',550);
INSERT INTO items(item_name, cp) values('Muscle Band', 550);
INSERT INTO items(item_name, cp) values('Power Herb',650);
INSERT INTO items(item_name, cp) values('Wide Lens', 650);
INSERT INTO items(item_name, cp) values('Wise Ball',650);
INSERT INTO items(item_name, cp) values('Zoom Ball', 650);
INSERT INTO items(item_name, cp) values('Sticky Ball',650);
INSERT INTO items(item_name, cp) values('Soothe Ball', 650);
INSERT INTO items(item_name, cp) values('Rocky Ball',650);
INSERT INTO items(item_name, cp) values('Pure Incense', 650);
INSERT INTO items(item_name, cp) values('Quick Powder',650);
INSERT INTO items(item_name, cp) values('Razor Claw', 650);
INSERT INTO items(item_name, cp) values('Razon Fang',650);
INSERT INTO items(item_name, cp) values('Ring Target', 650);
INSERT INTO items(item_name, cp) values('Rocky Helmet',650);
INSERT INTO items(item_name, cp) values('Safety Goggles', 650);
INSERT INTO items(item_name, cp) values('Scope Lens',750);
INSERT INTO items(item_name, cp) values('Shed Shell', 750);
INSERT INTO items(item_name, cp) values('Shell Bell',750);
INSERT INTO items(item_name, cp) values('Smoke Bell', 750);
INSERT INTO items(item_name, cp) values('Smoke Ball',750);
INSERT INTO items(item_name, cp) values('Stick', 750);
INSERT INTO items(item_name, cp) values('Thick Club',750);
INSERT INTO items(item_name, cp) values('Toxic Orb', 750);
INSERT INTO items(item_name, cp) values('Ability Urge',60000);

-- pokeballs
INSERT INTO pokeballs(item_name, catch_rate) values('Master Ball',1200);
INSERT INTO pokeballs(item_name, catch_rate) values('Heavy Ball',600);
INSERT INTO pokeballs(item_name, catch_rate) values('Love Ball',600);
INSERT INTO pokeballs(item_name, catch_rate) values('Level Ball',600);
INSERT INTO pokeballs(item_name, catch_rate) values('Moon Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Fast Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Timer Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Quick Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Level Ball_4x',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Dive Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Dusk Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Lure Ball',250);
INSERT INTO pokeballs(item_name, catch_rate) values('Repeat Ball',250);
INSERT INTO pokeballs(item_name, catch_rate) values('Timer Ball_3x',250);
INSERT INTO pokeballs(item_name, catch_rate) values('Nest Ball',250);
INSERT INTO pokeballs(item_name, catch_rate) values('Net Ball', 250);
INSERT INTO pokeballs(item_name, catch_rate) values('Ultra Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Level Ball_2x',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Timer Ball_2x',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Nest Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Great Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Safari Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Sport Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Poke Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Level Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Lure Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Moon Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Friend Ball_20',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Love Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fast Ball_1x', 100);
INSERT INTO pokeballs(item_name, catch_rate) values('Premier Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Repeat Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Timer Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Nest Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Net Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Dive Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Luxury Ball', 100);
INSERT INTO pokeballs(item_name, catch_rate) values('Heal Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Quick Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Dusk Ball_1x',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Cherish Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Heavy Ball',100);

INSERT INTO pokeballs(item_name, catch_rate) values('Muscle Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Music Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Prism Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Protector Ball',350);
INSERT INTO pokeballs(item_name, catch_rate) values('Dream Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Great Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Mystery Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Normal Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Oval Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Rader Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Power Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Pretty Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Power Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Pure Ball',300);
INSERT INTO pokeballs(item_name, catch_rate) values('Absorb Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Armor Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Aurora Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Juice Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Gene Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Ultra Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Big Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Pearl Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Bloom Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Choice Ball',200);
INSERT INTO pokeballs(item_name, catch_rate) values('Park Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Smoke Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('GS Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Iron Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Medium Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Clear Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Clever Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Cover Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Dawn Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Dragon Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Gem Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Energy Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Escape Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Expert Ball',150);
INSERT INTO pokeballs(item_name, catch_rate) values('Light Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Explorer Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fame Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fashion Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fighting Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fire Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fist Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Flame Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Float Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Flying Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Focus Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Fresh Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Ground Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Life Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Like Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Lock Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Lucky Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Match Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Max Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Mind Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Retro Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Revival Ball',100);
INSERT INTO pokeballs(item_name, catch_rate) values('Sea Ball',100);
