
-- combat_items

INSERT INTO items(item_name, price) values('X Attack',250);
INSERT INTO items(item_name, price) values('X Defense', 250);
INSERT INTO items(item_name, price) values('X SP. Atk',250);
INSERT INTO items(item_name, price) values('X SP. Def', 250);
INSERT INTO items(item_name, price) values('X Speed',250);
INSERT INTO items(item_name, price) values('X Accuracy', 250);
INSERT INTO items(item_name, price) values('Dire Hit',250);
INSERT INTO items(item_name, price) values('X Special', 250);
INSERT INTO items(item_name, price) values('X Attack_2',275);
INSERT INTO items(item_name, price) values('X Defense_2', 275);
INSERT INTO items(item_name, price) values('X SP. Atk_2',275);
INSERT INTO items(item_name, price) values('X SP. Def_2', 275);
INSERT INTO items(item_name, price) values('X Speed_2',275);
INSERT INTO items(item_name, price) values('X Accuracy_2', 275);
INSERT INTO items(item_name, price) values('Dire Hit_2',275);
INSERT INTO items(item_name, price) values('X Special_2', 275);
INSERT INTO items(item_name, price) values('X Attack_3',550);
INSERT INTO items(item_name, price) values('X Defense_3', 550);
INSERT INTO items(item_name, price) values('X SP. Atk_3',550);
INSERT INTO items(item_name, price) values('X SP. Def_3', 550);
INSERT INTO items(item_name, price) values('X Speed_3',550);
INSERT INTO items(item_name, price) values('X Accuracy_3', 550);
INSERT INTO items(item_name, price) values('Dire Hit_3',550);
INSERT INTO items(item_name, price) values('X Special_3', 550);
INSERT INTO items(item_name, price) values('X Attack_4',650);
INSERT INTO items(item_name, price) values('X Defense_4', 650);
INSERT INTO items(item_name, price) values('X SP. Atk_4',650);
INSERT INTO items(item_name, price) values('X SP. Def_4', 650);
INSERT INTO items(item_name, price) values('X Speed_4',650);
INSERT INTO items(item_name, price) values('X Accuracy_4', 650);
INSERT INTO items(item_name, price) values('Dire Hit_4',650);
INSERT INTO items(item_name, price) values('X Special_4', 650);
INSERT INTO items(item_name, price) values('X Attack_5',7650);
INSERT INTO items(item_name, price) values('X Defense_5', 750);
INSERT INTO items(item_name, price) values('X SP. Atk_5',750);
INSERT INTO items(item_name, price) values('X SP. Def_5', 750);
INSERT INTO items(item_name, price) values('X Speed_5',750);
INSERT INTO items(item_name, price) values('X Accuracy_5', 750);
INSERT INTO items(item_name, price) values('Dire Hit_5',750);
INSERT INTO items(item_name, price) values('X Special_5', 750);
INSERT INTO items(item_name, price) values('X Attack_6',500);
INSERT INTO items(item_name, price) values('X Defense_6', 500);
INSERT INTO items(item_name, price) values('X SP. Atk_6',500);
INSERT INTO items(item_name, price) values('X SP. Def_6', 500);
INSERT INTO items(item_name, price) values('X Speed_6',500);
INSERT INTO items(item_name, price) values('X Accuracy_6', 500);
INSERT INTO items(item_name, price) values('Dire Hit_6',500);
INSERT INTO items(item_name, price) values('X Special_6', 500);
INSERT INTO items(item_name, price) values('Guard Spec', 275);
INSERT INTO items(item_name, price) values('Item Drop', 275);
INSERT INTO items(item_name, price) values('Item Urge',275);
INSERT INTO items(item_name, price) values('Absorb Bulb', 275);
INSERT INTO items(item_name, price) values('Air Balloon', 275);
INSERT INTO items(item_name, price) values('Assault Vest',275);
INSERT INTO items(item_name, price) values('Big Root', 275);
INSERT INTO items(item_name, price) values('Binding Band', 275);
INSERT INTO items(item_name, price) values('Black Sludge',275);
INSERT INTO items(item_name, price) values('Reset Urge', 275);
INSERT INTO items(item_name, price) values('Start Urge',275);
INSERT INTO items(item_name, price) values('Bright Powder',550);
INSERT INTO items(item_name, price) values('Cell Battery', 550);
INSERT INTO items(item_name, price) values('Choice Band',550);
INSERT INTO items(item_name, price) values('Damp Rock', 550);
INSERT INTO items(item_name, price) values('Deep Sea Scale',550);
INSERT INTO items(item_name, price) values('Destiny Knot', 550);
INSERT INTO items(item_name, price) values('Eject Button',550);
INSERT INTO items(item_name, price) values('Float Stone', 550);
INSERT INTO items(item_name, price) values('Flame Orb', 550);
INSERT INTO items(item_name, price) values('Focus Band',550);
INSERT INTO items(item_name, price) values('Full Incense', 550);
INSERT INTO items(item_name, price) values('Grip Claw',650);
INSERT INTO items(item_name, price) values('Heat Rock', 650);
INSERT INTO items(item_name, price) values('Icy Rock',650);
INSERT INTO items(item_name, price) values('Iron Ball', 650);
INSERT INTO items(item_name, price) values('King Rock',650);
INSERT INTO items(item_name, price) values('Lucky Egg', 650);
INSERT INTO items(item_name, price) values('Lucky Punch',650);
INSERT INTO items(item_name, price) values('Mental Herb', 650);
INSERT INTO items(item_name, price) values('Metal Powder', 550);
INSERT INTO items(item_name, price) values('Metronome',550);
INSERT INTO items(item_name, price) values('Muscle Band', 550);
INSERT INTO items(item_name, price) values('Power Herb',650);
INSERT INTO items(item_name, price) values('Wide Lens', 650);
INSERT INTO items(item_name, price) values('Wise Ball',650);
INSERT INTO items(item_name, price) values('Zoom Ball', 650);
INSERT INTO items(item_name, price) values('Sticky Ball',650);
INSERT INTO items(item_name, price) values('Soothe Ball', 650);
INSERT INTO items(item_name, price) values('Rocky Ball',650);
INSERT INTO items(item_name, price) values('Pure Incense', 650);
INSERT INTO items(item_name, price) values('Quick Powder',650);
INSERT INTO items(item_name, price) values('Razor Claw', 650);
INSERT INTO items(item_name, price) values('Razon Fang',650);
INSERT INTO items(item_name, price) values('Ring Target', 650);
INSERT INTO items(item_name, price) values('Rocky Helmet',650);
INSERT INTO items(item_name, price) values('Safety Goggles', 650);
INSERT INTO items(item_name, price) values('Scope Lens',750);
INSERT INTO items(item_name, price) values('Shed Shell', 750);
INSERT INTO items(item_name, price) values('Shell Bell',750);
INSERT INTO items(item_name, price) values('Smoke Bell', 750);
INSERT INTO items(item_name, price) values('Smoke Ball',750);
INSERT INTO items(item_name, price) values('Stick', 750);
INSERT INTO items(item_name, price) values('Thick Club',750);
INSERT INTO items(item_name, price) values('Toxic Orb', 750);
INSERT INTO items(item_name, price) values('Ability Urge',60000);

-- pokeballs

INSERT INTO items(item_name, price) values('Master Ball',1200);
INSERT INTO items(item_name, price) values('Heavy Ball',600);
INSERT INTO items(item_name, price) values('Love Ball',600);
INSERT INTO items(item_name, price) values('Level Ball',600);
INSERT INTO items(item_name, price) values('Moon Ball',350);
INSERT INTO items(item_name, price) values('Fast Ball',350);
INSERT INTO items(item_name, price) values('Timer Ball',350);
INSERT INTO items(item_name, price) values('Quick Ball',350);
INSERT INTO items(item_name, price) values('Level Ball_4x',350);
INSERT INTO items(item_name, price) values('Dive Ball',300);
INSERT INTO items(item_name, price) values('Dusk Ball',300);
INSERT INTO items(item_name, price) values('Lure Ball',250);
INSERT INTO items(item_name, price) values('Repeat Ball',250);
INSERT INTO items(item_name, price) values('Timer Ball_3x',250);
INSERT INTO items(item_name, price) values('Nest Ball',250);
INSERT INTO items(item_name, price) values('Net Ball', 250);
INSERT INTO items(item_name, price) values('Ultra Ball',200);
INSERT INTO items(item_name, price) values('Level Ball_2x',200);
INSERT INTO items(item_name, price) values('Timer Ball_2x',200);
INSERT INTO items(item_name, price) values('Nest Ball',200);
INSERT INTO items(item_name, price) values('Great Ball',150);
INSERT INTO items(item_name, price) values('Safari Ball',150);
INSERT INTO items(item_name, price) values('Sport Ball',150);
INSERT INTO items(item_name, price) values('Poke Ball',100);
INSERT INTO items(item_name, price) values('Level Ball_1x',100);
INSERT INTO items(item_name, price) values('Lure Ball_1x',100);
INSERT INTO items(item_name, price) values('Moon Ball_1x',100);
INSERT INTO items(item_name, price) values('Friend Ball_20',100);
INSERT INTO items(item_name, price) values('Love Ball',100);
INSERT INTO items(item_name, price) values('Fast Ball_1x', 100);
INSERT INTO items(item_name, price) values('Premier Ball',100);
INSERT INTO items(item_name, price) values('Repeat Ball_1x',100);
INSERT INTO items(item_name, price) values('Timer Ball_1x',100);
INSERT INTO items(item_name, price) values('Nest Ball_1x',100);
INSERT INTO items(item_name, price) values('Net Ball_1x',100);
INSERT INTO items(item_name, price) values('Dive Ball_1x',100);
INSERT INTO items(item_name, price) values('Luxury Ball', 100);
INSERT INTO items(item_name, price) values('Heal Ball',100);
INSERT INTO items(item_name, price) values('Quick Ball_1x',100);
INSERT INTO items(item_name, price) values('Dusk Ball_1x',100);
INSERT INTO items(item_name, price) values('Cherish Ball',100);
INSERT INTO items(item_name, price) values('Heavy Ball',100);

INSERT INTO items(item_name, price) values('Muscle Ball',350);
INSERT INTO items(item_name, price) values('Music Ball',350);
INSERT INTO items(item_name, price) values('Prism Ball',350);
INSERT INTO items(item_name, price) values('Protector Ball',350);
INSERT INTO items(item_name, price) values('Dream Ball',300);
INSERT INTO items(item_name, price) values('Great Ball',300);
INSERT INTO items(item_name, price) values('Mystery Ball',300);
INSERT INTO items(item_name, price) values('Normal Ball',300);
INSERT INTO items(item_name, price) values('Oval Ball',300);
INSERT INTO items(item_name, price) values('Rader Ball',300);
INSERT INTO items(item_name, price) values('Power Ball',300);
INSERT INTO items(item_name, price) values('Pretty Ball',300);
INSERT INTO items(item_name, price) values('Power Ball',300);
INSERT INTO items(item_name, price) values('Pure Ball',300);
INSERT INTO items(item_name, price) values('Absorb Ball',200);
INSERT INTO items(item_name, price) values('Armor Ball',200);
INSERT INTO items(item_name, price) values('Aurora Ball',200);
INSERT INTO items(item_name, price) values('Juice Ball',200);
INSERT INTO items(item_name, price) values('Gene Ball',200);
INSERT INTO items(item_name, price) values('Ultra Ball',200);
INSERT INTO items(item_name, price) values('Big Ball',200);
INSERT INTO items(item_name, price) values('Pearl Ball',200);
INSERT INTO items(item_name, price) values('Bloom Ball',200);
INSERT INTO items(item_name, price) values('Choice Ball',200);
INSERT INTO items(item_name, price) values('Park Ball',150);
INSERT INTO items(item_name, price) values('Smoke Ball',150);
INSERT INTO items(item_name, price) values('GS Ball',150);
INSERT INTO items(item_name, price) values('Iron Ball',150);
INSERT INTO items(item_name, price) values('Medium Ball',150);
INSERT INTO items(item_name, price) values('Clear Ball',150);
INSERT INTO items(item_name, price) values('Clever Ball',150);
INSERT INTO items(item_name, price) values('Cover Ball',150);
INSERT INTO items(item_name, price) values('Dawn Ball',150);
INSERT INTO items(item_name, price) values('Dragon Ball',150);
INSERT INTO items(item_name, price) values('Gem Ball',150);
INSERT INTO items(item_name, price) values('Energy Ball',150);
INSERT INTO items(item_name, price) values('Escape Ball',150);
INSERT INTO items(item_name, price) values('Expert Ball',150);
INSERT INTO items(item_name, price) values('Light Ball',100);
INSERT INTO items(item_name, price) values('Explorer Ball',100);
INSERT INTO items(item_name, price) values('Fame Ball',100);
INSERT INTO items(item_name, price) values('Fashion Ball',100);
INSERT INTO items(item_name, price) values('Fighting Ball',100);
INSERT INTO items(item_name, price) values('Fire Ball',100);
INSERT INTO items(item_name, price) values('Fist Ball',100);
INSERT INTO items(item_name, price) values('Flame Ball',100);
INSERT INTO items(item_name, price) values('Float Ball',100);
INSERT INTO items(item_name, price) values('Flying Ball',100);
INSERT INTO items(item_name, price) values('Focus Ball',100);
INSERT INTO items(item_name, price) values('Fresh Ball',100);
INSERT INTO items(item_name, price) values('Ground Ball',100);
INSERT INTO items(item_name, price) values('Life Ball',100);
INSERT INTO items(item_name, price) values('Like Ball',100);
INSERT INTO items(item_name, price) values('Lock Ball',100);
INSERT INTO items(item_name, price) values('Lucky Ball',100);
INSERT INTO items(item_name, price) values('Match Ball',100);
INSERT INTO items(item_name, price) values('Max Ball',100);
INSERT INTO items(item_name, price) values('Mind Ball',100);
INSERT INTO items(item_name, price) values('Retro Ball',100);
INSERT INTO items(item_name, price) values('Revival Ball',100);
INSERT INTO items(item_name, price) values('Sea Ball',100);

-- healing_items

INSERT INTO items(item_name, price) values('Max Potion', 750);
INSERT INTO items(item_name, price) values('Max Elixir', 300);
INSERT INTO items(item_name, price) values('Max Revive', 300);
INSERT INTO items(item_name, price) values('Max Revive', 300);
INSERT INTO items(item_name, price) values('Rage Candy Bar', 300);
INSERT INTO items(item_name, price) values('Revival Herb', 300);
INSERT INTO items(item_name, price) values('Sacred Ash', 300);
INSERT INTO items(item_name, price) values('Sweet Heart', 300);
INSERT INTO items(item_name, price) values('Green Candycane', 250);
INSERT INTO items(item_name, price) values('Halloween Candy', 200);
INSERT INTO items(item_name, price) values('Pumpkin', 200);
INSERT INTO items(item_name, price) values('Revive', 200);
INSERT INTO items(item_name, price) values('Hyper Potion', 200);
INSERT INTO items(item_name, price) values('Red Candycane', 200);
INSERT INTO items(item_name, price) values('Lumiose Galette', 150);
INSERT INTO items(item_name, price) values('Secret Potion', 200);
INSERT INTO items(item_name, price) values('Elixir', 200);
INSERT INTO items(item_name, price) values('Ether', 200);
INSERT INTO items(item_name, price) values('Old Gateau', 100);
INSERT INTO items(item_name, price) values('Casteliacone', 100);
INSERT INTO items(item_name, price) values('Shalour Sable', 100);
INSERT INTO items(item_name, price) values('Lemonade', 100);
INSERT INTO items(item_name, price) values('MooMoo Milk', 100);
INSERT INTO items(item_name, price) values('Lava Cookie', 100);
INSERT INTO items(item_name, price) values('Soda Pop', 60);
INSERT INTO items(item_name, price) values('Super Potion', 50);
INSERT INTO items(item_name, price) values('Awakening', 50);
INSERT INTO items(item_name, price) values('Burn Heal', 50);
INSERT INTO items(item_name, price) values('Ice Heal', 50);
INSERT INTO items(item_name, price) values('Heat Heal', 50);
INSERT INTO items(item_name, price) values('Frozen Heal', 50);
INSERT INTO items(item_name, price) values('Full Heal', 50);
INSERT INTO items(item_name, price) values('Full Restore', 50);
INSERT INTO items(item_name, price) values('Fresh Water', 50);
INSERT INTO items(item_name, price) values('Rainbow Candycane', 50);
INSERT INTO items(item_name, price) values('Cheri Berry', 50);
INSERT INTO items(item_name, price) values('Chesto Berry', 50);
INSERT INTO items(item_name, price) values('Pecha Berry', 50);
INSERT INTO items(item_name, price) values('Rawst Berry', 50);
INSERT INTO items(item_name, price) values('Aspear Berry', 50);
INSERT INTO items(item_name, price) values('Leppa Berry', 50);
INSERT INTO items(item_name, price) values('Oran Berry', 50);
INSERT INTO items(item_name, price) values('Persim Berry', 50);
INSERT INTO items(item_name, price) values('Lum Berry', 50);
INSERT INTO items(item_name, price) values('Sitrus Berry', 50);
INSERT INTO items(item_name, price) values('Figy Berry', 50);
INSERT INTO items(item_name, price) values('Wiki Berry', 50);
INSERT INTO items(item_name, price) values('Mago Berry', 50);
INSERT INTO items(item_name, price) values('Aguav Berry', 50);
INSERT INTO items(item_name, price) values('Iapapa Berry', 50);
INSERT INTO items(item_name, price) values('Razz Berry', 50);
INSERT INTO items(item_name, price) values('Bluk Berry', 50);
INSERT INTO items(item_name, price) values('Nanab Berry', 50);
INSERT INTO items(item_name, price) values('Wepear Berry', 50);
INSERT INTO items(item_name, price) values('Pinap Berry', 50);
INSERT INTO items(item_name, price) values('Pomeg Berry', 50);
INSERT INTO items(item_name, price) values('Kelpsy Berry', 50);
INSERT INTO items(item_name, price) values('Qualot Berry', 50);
INSERT INTO items(item_name, price) values('Hondew Berry', 50);
INSERT INTO items(item_name, price) values('Grepa Berry', 50);
INSERT INTO items(item_name, price) values('Tamato Berry', 50);
INSERT INTO items(item_name, price) values('Cornn Berry', 20);
INSERT INTO items(item_name, price) values('Magost Berry', 20);
INSERT INTO items(item_name, price) values('Rabuta Berry', 20);
INSERT INTO items(item_name, price) values('Nomel Berry', 20);
INSERT INTO items(item_name, price) values('Spelon Berry', 20);
INSERT INTO items(item_name, price) values('Pamter Berry', 20);
INSERT INTO items(item_name, price) values('Watmel Berry', 20);
INSERT INTO items(item_name, price) values('Durin Berry', 20);
INSERT INTO items(item_name, price) values('Belue Berry', 20);
INSERT INTO items(item_name, price) values('Occa Berry', 20);
INSERT INTO items(item_name, price) values('Passho Berry', 20);
INSERT INTO items(item_name, price) values('Wacan Berry', 20);
INSERT INTO items(item_name, price) values('Rindo Berry', 20);
INSERT INTO items(item_name, price) values('Yache Berry', 20);
INSERT INTO items(item_name, price) values('Potion', 20);
INSERT INTO items(item_name, price) values('Antidote', 20);
INSERT INTO items(item_name, price) values('Paralyze Heal', 20);
INSERT INTO items(item_name, price) values('Berry Juice', 20);
INSERT INTO items(item_name, price) values('Orange Juice', 20);
INSERT INTO items(item_name, price) values('Apple Juice', 20);
INSERT INTO items(item_name, price) values('Melon Juice', 20);
INSERT INTO items(item_name, price) values('Chocolate Bar', 10);
INSERT INTO items(item_name, price) values('Chople Berry', 10);
INSERT INTO items(item_name, price) values('Kebia Berry', 10);
INSERT INTO items(item_name, price) values('Shuca Berry', 10);
INSERT INTO items(item_name, price) values('Coba Berry', 10);
INSERT INTO items(item_name, price) values('Payapa Berry', 10);
INSERT INTO items(item_name, price) values('Tanga Berry', 10);
INSERT INTO items(item_name, price) values('Charati Berry', 10);
INSERT INTO items(item_name, price) values('Kasib Berry', 10);
INSERT INTO items(item_name, price) values('Haban Berry', 10);
INSERT INTO items(item_name, price) values('Colbur Berry', 10);
INSERT INTO items(item_name, price) values('Babiri Berry', 10);
INSERT INTO items(item_name, price) values('Chilan Berry', 10);
INSERT INTO items(item_name, price) values('Liechi Berry', 10);
INSERT INTO items(item_name, price) values('Ganlon Berry', 10);

INSERT INTO items(item_name, price) values('Salac Berry', 10);
INSERT INTO items(item_name, price) values('Petaya Berry', 10);
INSERT INTO items(item_name, price) values('Apicot Berry', 10);
INSERT INTO items(item_name, price) values('Lansat Berry', 10);
INSERT INTO items(item_name, price) values('Starf Berry', 10);
