insert into members (gym_num,trainer_name,city_name) values (1,'Brandon','Summit Hill');
insert into members (gym_num,trainer_name,city_name) values (2,'Jodie','Sunrise Beach');
insert into members (gym_num,trainer_name,city_name) values (2,'Laura','Sunrise Beach');
insert into members (gym_num,trainer_name,city_name) values (2,'Miles','Sunrise Beach');
insert into members (gym_num,trainer_name,city_name) values (13,'Brandon','North Albany');
insert into members (gym_num,trainer_name,city_name) values (24,'Brian','Shallow Water');
insert into members (gym_num,trainer_name,city_name) values (24,'Glenn','Shallow Water');
insert into members (gym_num,trainer_name,city_name) values (24,'Jack','Shallow Water');
insert into members (gym_num,trainer_name,city_name) values (27,'Jack','Uncasville');
insert into members (gym_num,trainer_name,city_name) values (27,'Brian','Uncasville');
insert into members (gym_num,trainer_name,city_name) values (27,'Glenn','Uncasville');
insert into members (gym_num,trainer_name,city_name) values (33,'Corri','Waldorf');
insert into members (gym_num,trainer_name,city_name) values (34,'Jack','West Forks');
insert into members (gym_num,trainer_name,city_name) values (34,'Glenn','West Forks');
insert into members (gym_num,trainer_name,city_name) values (35,'Cory','Yardley');
insert into members (gym_num,trainer_name,city_name) values (39,'Milo','Arizona City');
insert into members (gym_num,trainer_name,city_name) values (40,'Anna','Atlantic City');
insert into members (gym_num,trainer_name,city_name) values (40,'Scottie','Atlantic City');
insert into members (gym_num,trainer_name,city_name) values (44,'Cory','Francis Mills');
insert into members (gym_num,trainer_name,city_name) values (45,'Milo','German Valley');
insert into members (gym_num,trainer_name,city_name) values (48,'Anna','Imperial Beach');
insert into members (gym_num,trainer_name,city_name) values (48,'Scottie','Imperial Beach');
insert into members (gym_num,trainer_name,city_name) values (53,'Anna','Kettle River');
insert into members (gym_num,trainer_name,city_name) values (53,'Scottie','Kettle River');
insert into members (gym_num,trainer_name,city_name) values (55,'Laura','Ladera Heights');
insert into members (gym_num,trainer_name,city_name) values (55,'Miles','Ladera Heights');
insert into members (gym_num,trainer_name,city_name) values (56,'Jeff','Lane City');
insert into members (gym_num,trainer_name,city_name) values (56,'Levi','Lane City');
insert into members (gym_num,trainer_name,city_name) values (57,'Corri','Las Vegas');
insert into members (gym_num,trainer_name,city_name) values (57,'Cory','Las Vegas');
insert into members (gym_num,trainer_name,city_name) values (58,'Brandon','Manassas Park');
insert into members (gym_num,trainer_name,city_name) values (59,'Anna','Marvell');
insert into members (gym_num,trainer_name,city_name) values (59,'Scottie','Marvell');
insert into members (gym_num,trainer_name,city_name) values (62,'Scottie','Gulf Crest');
insert into members (gym_num,trainer_name,city_name) values (62,'Anna','Gulf Crest');
insert into members (gym_num,trainer_name,city_name) values (67,'Denise','Lake Wisconsin');
insert into members (gym_num,trainer_name,city_name) values (69,'Levi','Ipswich');
insert into members (gym_num,trainer_name,city_name) values (69,'Jeff','Ipswich');
insert into members (gym_num,trainer_name,city_name) values (71,'Ellen','Railroad');
insert into members (gym_num,trainer_name,city_name) values (71,'Henry','Railroad');
insert into members (gym_num,trainer_name,city_name) values (88,'Levi','Fountain Hill');
insert into members (gym_num,trainer_name,city_name) values (88,'Jeff','Fountain Hill');
insert into members (gym_num,trainer_name,city_name) values (102,'Henry','Cherry');
insert into members (gym_num,trainer_name,city_name) values (102,'Ellen','Cherry');
insert into members (gym_num,trainer_name,city_name) values (107,'Nick','Alamo');
insert into members (gym_num,trainer_name,city_name) values (111,'Nick','Labouchere Bay');
insert into members (gym_num,trainer_name,city_name) values (112,'Henry','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (112,'Ellen','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (113,'Nick','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (115,'Henry','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (115,'Ellen','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (117,'Isabella','Arizona City');
insert into members (gym_num,trainer_name,city_name) values (117,'Jamie','Arizona City');
insert into members (gym_num,trainer_name,city_name) values (123,'Isabella','Raymond');
insert into members (gym_num,trainer_name,city_name) values (123,'Scott','Raymond');
insert into members (gym_num,trainer_name,city_name) values (124,'Ava','Raymond');
insert into members (gym_num,trainer_name,city_name) values (124,'Jodie','Raymond');
insert into members (gym_num,trainer_name,city_name) values (124,'Miles','Raymond');
insert into members (gym_num,trainer_name,city_name) values (125,'Ava','North Albany');
insert into members (gym_num,trainer_name,city_name) values (125,'Jodie','North Albany');
insert into members (gym_num,trainer_name,city_name) values (125,'Miles','North Albany');
insert into members (gym_num,trainer_name,city_name) values (127,'Ava','Oakford');
insert into members (gym_num,trainer_name,city_name) values (127,'Jodie','Oakford');
insert into members (gym_num,trainer_name,city_name) values (127,'Miles','Oakford');
insert into members (gym_num,trainer_name,city_name) values (129,'Jodie','Raymond');
insert into members (gym_num,trainer_name,city_name) values (129,'Miles','Raymond');
insert into members (gym_num,trainer_name,city_name) values (130,'Corri','Pageland');
insert into members (gym_num,trainer_name,city_name) values (131,'Atticus','North Albany');
insert into members (gym_num,trainer_name,city_name) values (134,'Isabella','Octavia');
insert into members (gym_num,trainer_name,city_name) values (134,'Scott','Octavia');
insert into members (gym_num,trainer_name,city_name) values (137,'Nick','Peabody');
insert into members (gym_num,trainer_name,city_name) values (138,'Corri','Raymond');
insert into members (gym_num,trainer_name,city_name) values (138,'Atticus','Raymond');
insert into members (gym_num,trainer_name,city_name) values (147,'Isabella','Raymond');
insert into members (gym_num,trainer_name,city_name) values (147,'Scott','Raymond');
insert into members (gym_num,trainer_name,city_name) values (161,'Tom','Francis Mills');
insert into members (gym_num,trainer_name,city_name) values (170,'Mick','Kansas City');
insert into members (gym_num,trainer_name,city_name) values (173,'Tom','Ladera Heights');
insert into members (gym_num,trainer_name,city_name) values (174,'Mick','Lane City');
insert into members (gym_num,trainer_name,city_name) values (176,'Liam','Manassas Park');
insert into members (gym_num,trainer_name,city_name) values (177,'Liam','Marvell');
insert into members (gym_num,trainer_name,city_name) values (179,'Tom','Nelagoney');
insert into members (gym_num,trainer_name,city_name) values (181,'Liam','Frackville');
insert into members (gym_num,trainer_name,city_name) values (188,'Geoff','Quincy');
insert into members (gym_num,trainer_name,city_name) values (188,'Will','Quincy');
insert into members (gym_num,trainer_name,city_name) values (189,'Isabella','Railroad');
insert into members (gym_num,trainer_name,city_name) values (189,'Jamie','Railroad');
insert into members (gym_num,trainer_name,city_name) values (190,'Tom','Rainbow City');
insert into members (gym_num,trainer_name,city_name) values (192,'Geoff','Saint Elmo');
insert into members (gym_num,trainer_name,city_name) values (192,'Will','Saint Elmo');
insert into members (gym_num,trainer_name,city_name) values (193,'Geoff','Tampa');
insert into members (gym_num,trainer_name,city_name) values (193,'Will','Tampa');
insert into members (gym_num,trainer_name,city_name) values (194,'Geoff','Thunderbolt');
insert into members (gym_num,trainer_name,city_name) values (194,'Will','Thunderbolt');
insert into members (gym_num,trainer_name,city_name) values (195,'Will','Topeka');
insert into members (gym_num,trainer_name,city_name) values (197,'Tom','Virgin');
insert into members (gym_num,trainer_name,city_name) values (198,'Isabella','Wahoo');
insert into members (gym_num,trainer_name,city_name) values (198,'Jamie','Wahoo');
insert into members (gym_num,trainer_name,city_name) values (202,'Isabella','Amorita');
insert into members (gym_num,trainer_name,city_name) values (202,'Jamie','Amorita');
