insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Sophia','Summit Hill');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Ava','Sunrise Beach');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','Tom','Waldwick');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Harper','Abilene');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Liam','Alamo');
insert into gyms (badge,leader_name,city_name) values ('Wave Badge','Kerry','Cedartown');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Declan','Cherry');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Tom','Harrison');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Harper','Keeneland');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Liam','Key West');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Frank','Kinsey');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Declan','Norbeck');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Sophia','North Albany');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Dee','Northfork');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Frank','Oakford');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Frank','Octavia');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Kerry','Pageland');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Frank','Palm City');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Kerry','Panama City');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Dee','Peabody');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Asher','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Liam','Reddick');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Dee','Sanchez');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Mason','Shallow Water');
insert into gyms (badge,leader_name,city_name) values ('Legend Badge','Kerry','Tundra');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Harper','Udall');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Mason','Uncasville');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Dee','Tulalip Bay');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Norman','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Frank','Valley View');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Adam','Violet Hill');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Olivia','Wading River');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Atticus','Waldorf');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Mason','West Forks');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Blake','Yardley');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Norman','Zelienople');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','James','Zolfo Springs');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Michael','Adel');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Ezra','Arizona City');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Jolene','Atlantic City');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Tom','Dime Box');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','James','Dunwoody');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Norman','Gas City');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Atticus','Francis Mills');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Ezra','German Valley');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Milo','Hahira');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Kerry','Hamilton City');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Jolene','Imperial Beach');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Harper','Hendrum');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Liam','Indianapolis');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Milo','Jacksboro');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Milo','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Jolene','Kettle River');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Asher','Labouchere Bay');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','Ava','Ladera Heights');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Abigail','Lane City');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Atticus','Las Vegas');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Sophia','Manassas Park');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Jolene','Marvell');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Milo','Milwaukee');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Blake','Nelagoney');
insert into gyms (badge,leader_name,city_name) values ('Wave Badge','Jolene','Gulf Crest');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','James','Frackville');
insert into gyms (badge,leader_name,city_name) values ('Legend Badge','Tom','New Chicago');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Barbara','Pilsen');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Michael','Lathrup Village');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Mick','Lake Wisconsin');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Mick','Iowa');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Abigail','Ipswich');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Milo','Quincy');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Silas','Railroad');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Jasper','Rainbow City');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Mick','River Rouge');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Jasper','Saint Elmo');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Mick','Tampa');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','Milo','Thunderbolt');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Andreas','Topeka');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Andreas','Universal City');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Harper','Virgin');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Barbara','Wahoo');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Asher','West Sunbury');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Andreas','Y City');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Barbara','Zapata');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Jasper','Amorita');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Jasper','Apache Junction');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Milo','Decatur');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Nicholas','Fort Ripley');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Abigail','Fountain Hill');
insert into gyms (badge,leader_name,city_name) values ('Wave Badge','Michael','Garden Acres');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Jasper','Glenmoor');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Jasper','Gran Quivira');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Barbara','Grandfield');
insert into gyms (badge,leader_name,city_name) values ('Coral-Eye Badge','Jasper','Hamorton');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Matt','Jasmine Estates');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Asher','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Blake','Kachemak City');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Nicholas','Las Animas');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Jasper','Waldwick');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Nicholas','Abilene');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Michael','Alamo');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Blake','Cedartown');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Silas','Cherry');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Charlotte','Harrison');
insert into gyms (badge,leader_name,city_name) values ('Sea Ruby Badge','Matt','Keeneland');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','Matt','Key West');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Nicholas','Abilene');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','David','Alamo');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Nicholas','Cedartown');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Erica','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Wave Badge','Nicholas','Kettle River');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','David','Labouchere Bay');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Silas','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Jade Star Badge','David','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','Asher','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Silas','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Erica','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Legend Badge','Scott','Arizona City');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Nicholas','Atlantic City');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Nicholas','Arizona City');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Charlotte','Atlantic City');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Samantha','Arizona City');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Samantha','Atlantic City');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Jamie','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Laura','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Laura','North Albany');
insert into gyms (badge,leader_name,city_name) values ('Sea Ruby Badge','Erica','Northfork');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Laura','Oakford');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','David','Octavia');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Laura','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Bug Badge','Cory','Pageland');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Cory','North Albany');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Norman','Northfork');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Cory','Oakford');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Jamie','Octavia');
insert into gyms (badge,leader_name,city_name) values ('Fairy Badge','Norman','Pageland');
insert into gyms (badge,leader_name,city_name) values ('Cliff Badge','Benjamin','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','David','Peabody');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Cory','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','Charlotte','Reddick');
insert into gyms (badge,leader_name,city_name) values ('Sea Ruby Badge','Nicholas','Shallow Water');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Dee','Sanchez');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','David','Sparta');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Amy','Tundra');
insert into gyms (badge,leader_name,city_name) values ('Cliff Badge','David','Udall');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Jamie','Uncasville');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Amy','Tulalip Bay');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Jamie','Raymond');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Blake','Valley View');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','Dee','Violet Hill');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Eli','Wading River');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Eli','Waldorf');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','Amy','West Forks');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Amy','Yardley');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Eli','Zelienople');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Blake','Zolfo Springs');
insert into gyms (badge,leader_name,city_name) values ('Sea Ruby Badge','Samantha','Adel');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Eli','Arizona City');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','Yuri','Atlantic City');
insert into gyms (badge,leader_name,city_name) values ('Legend Badge','Charlotte','Dime Box');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Samantha','Dunwoody');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Thomas','Francis Mills');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Benjamin','Gas City');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Blake','German Valley');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Courtenay','Hahira');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Courtenay','Hamilton City');
insert into gyms (badge,leader_name,city_name) values ('Cliff Badge','Yuri','Hendrum');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','William','Imperial Beach');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Eli','Indianapolis');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Blake','Jacksboro');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Denise','Kansas City');
insert into gyms (badge,leader_name,city_name) values ('Spike Shell Badge','Yuri','Kettle River');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Blake','Labouchere Bay');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Thomas','Ladera Heights');
insert into gyms (badge,leader_name,city_name) values ('Sea Ruby Badge','Denise','Lane City');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Amy','Las Vegas');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Ian','Manassas Park');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Ian','Marvell');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Jodie','Milwaukee');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Thomas','Nelagoney');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','William','Gulf Crest');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','Ian','Frackville');
insert into gyms (badge,leader_name,city_name) values ('Iceberg Badge','Geoffery','New Chicago');
insert into gyms (badge,leader_name,city_name) values ('Freeze Badge','Geoffery','Pilsen');
insert into gyms (badge,leader_name,city_name) values ('Psychic Badge','Emma','Lathrup Village');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Jodie','Lake Wisconsin');
insert into gyms (badge,leader_name,city_name) values ('Legend Badge','Jodie','Iowa');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Courtenay','Ipswich');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Craig','Quincy');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Scott','Railroad');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Thomas','Rainbow City');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Jodie','River Rouge');
insert into gyms (badge,leader_name,city_name) values ('Voltage Badge','Craig','Saint Elmo');
insert into gyms (badge,leader_name,city_name) values ('Plant Badge','Craig','Tampa');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Craig','Thunderbolt');
insert into gyms (badge,leader_name,city_name) values ('Rumble Badge','Craig','Topeka');
insert into gyms (badge,leader_name,city_name) values ('Cliff Badge','Thomas','Universal City');
insert into gyms (badge,leader_name,city_name) values ('Insect Badge','Norman','Virgin');
insert into gyms (badge,leader_name,city_name) values ('Bolt Badge','Scott','Wahoo');
insert into gyms (badge,leader_name,city_name) values ('Jet Badge','William','West Sunbury');
insert into gyms (badge,leader_name,city_name) values ('Toxic Badge','Emma','Y City');
insert into gyms (badge,leader_name,city_name) values ('Quake Badge','Benjamin','Zapata');
insert into gyms (badge,leader_name,city_name) values ('Trio Badge','Scott','Amorita');
insert into gyms (badge,leader_name,city_name) values ('Basic Badge','Emma','Apache Junction');
