insert into stores_items(city_name,loc,item_name) values ('Stony River','Indiana','X Attack');
insert into stores_items(city_name,loc,item_name)  values ('Sugarloaf','Rio de Janeiro','X Defense');
insert into stores_items(city_name,loc,item_name) values ('Summit Hill','Dallas','X Defense');
insert into stores_items(city_name,loc,item_name)  values ('Sunrise Beach','Missouri','X Attack');
insert into stores_items(city_name,loc,item_name) values ('Waldwick','New Jersey','X SP. Atk');
insert into stores_items(city_name,loc,item_name) values ('Abilene','Brooklyn','Dire Hit');
insert into stores_items(city_name,loc,item_name)  values ('Alamo','New York','X Special');
insert into stores_items(city_name,loc,item_name) values ('Cedartown','Georgia','X Attack_2');
insert into stores_items(city_name,loc,item_name) values ('Cherry','Alabama','X Special');
insert into stores_items(city_name,loc,item_name) values ('Harrison','Virginia','X Defense_2');
insert into stores_items(city_name,loc,item_name)  values ('Keeneland','Kentucky','X Attack_2');
insert into stores_items(city_name,loc,item_name) values ('Key West','Florida','X SP. Atk_2');
insert into stores_items(city_name,loc,item_name) values ('Kinsey','Texas','X Defense_2');
insert into stores_items(city_name,loc,item_name)  values ('Norbeck','Washington','X SP. Def_2');
insert into stores_items(city_name,loc,item_name) values ('North Albany','New Jersey','X Speed_2');
insert into stores_items(city_name,loc,item_name) values ('Northfork','West Virginia','X SP. Atk_2');
insert into stores_items(city_name,loc,item_name) values ('Oakford','Baltimore','X SP. Def_2');
insert into stores_items(city_name,loc,item_name) values ('Octavia','San Francisco','X SP. Def');
insert into stores_items(city_name,loc,item_name) values ('Pageland','South Carolina','X Accuracy');
insert into stores_items(city_name,loc,item_name) values ('Palm City','Florida','X Accuracy');
insert into stores_items(city_name,loc,item_name) values ('Panama City','Florida','X SP. Atk');
insert into stores_items(city_name,loc,item_name) values ('Peabody','Massachusetts','X Speed');
insert into stores_items(city_name,loc,item_name) values ('Raymond','New Hampshire','Dire Hit');
insert into stores_items(city_name,loc,item_name) values ('Reddick','Illinois','X Speed_2');
insert into stores_items(city_name,loc,item_name) values ('Sanchez','Chicago','X Accuracy_2');
insert into stores_items(city_name,loc,item_name) values ('Shallow Water','Indiana','X Attack');
insert into stores_items(city_name,loc,item_name) values ('Sparta','Tennessee','X Speed');
insert into stores_items(city_name,loc,item_name) values ('Tundra','Missouri','X Accuracy_2');
insert into stores_items(city_name,loc,item_name) values ('Udall','Kansas','X Speed_2');
insert into stores_items(city_name,loc,item_name) values ('Uncasville','Connecticut','X Defense_3');
insert into stores_items(city_name,loc,item_name) values ('Tulalip Bay','Washington','X Attack_4');
insert into stores_items(city_name,loc,item_name)  values ('Valley View','Washington','Dire Hit_3');
insert into stores_items(city_name,loc,item_name) values ('Violet Hill','California','Dire Hit_3');
insert into stores_items(city_name,loc,item_name) values ('Wading River','New York','X Attack_3');
insert into stores_items(city_name,loc,item_name)  values ('Waldorf','Maryland','X Defense_3');
insert into stores_items(city_name,loc,item_name) values ('West Forks','Arizona','X Attack_4');
insert into stores_items(city_name,loc,item_name) values ('Yardley','Pennsylvania','X Defense_4');
insert into stores_items(city_name,loc,item_name) values ('Zelienople','Pennsylvania','X Attack_3');
insert into stores_items(city_name,loc,item_name) values ('Zolfo Springs','Florida','X Defense_4');
insert into stores_items(city_name,loc,item_name) values ('Adel','Georgia','X Accuracy_4');
insert into stores_items(city_name,loc,item_name)  values ('Arizona City','Arizona','Dire Hit_4');
insert into stores_items(city_name,loc,item_name) values ('Atlantic City','New Jersey','Dire Hit_4');
insert into stores_items(city_name,loc,item_name) values ('Dime Box','Texas','X Accuracy_4','X Special_4');
insert into stores_items(city_name,loc,item_name) values ('Dunwoody','Georgia','X Special_4');
insert into stores_items(city_name,loc,item_name) values ('Francis Mills','New Jersey','X Attack_5');
insert into stores_items(city_name,loc,item_name)  values ('Gas City','Indiana','X Defense_5');
insert into stores_items(city_name,loc,item_name) values ('German Valley','Illinois','X Defense_5');
insert into stores_items(city_name,loc,item_name) values ('Hahira','Georgia','X Attack_5');
insert into stores_items(city_name,loc,item_name) values ('Hamilton City','Ohio','Guard Spec');
insert into stores_items(city_name,loc,item_name)  values ('Hendrum','Minnesota','Guard Spec');
insert into stores_items(city_name,loc,item_name)  values ('Imperial Beach','California','Item Drop');
insert into stores_items(city_name,loc,item_name) values ('Indianapolis','Indiana','Item Urge');
insert into stores_items(city_name,loc,item_name) values ('Jacksboro','Texas','Item Urge');
insert into stores_items(city_name,loc,item_name) values ('Kansas City','Kansas','Absorb Bulb');
insert into stores_items(city_name,loc,item_name) values ('Kettle River','Wyoming','Air Balloon');
insert into stores_items(city_name,loc,item_name) values ('Labouchere Bay','Canada','Air Balloon');
insert into stores_items(city_name,loc,item_name) values ('Ladera Heights','California','Assault Vest');
insert into stores_items(city_name,loc,item_name) values ('Lane City','Oregon','Assault Vest');
insert into stores_items(city_name,loc,item_name)  values ('Las Vegas','Nevada','Big Root');
insert into stores_items(city_name,loc,item_name)  values ('Manassas Park','Virginia','Big Root');
insert into stores_items(city_name,loc,item_name) values ('Marvell','Arkansas','Binding Band');
insert into stores_items(city_name,loc,item_name) values ('Milwaukee','Wisconsin','Binding Band');
insert into stores_items(city_name,loc,item_name) values ('Nelagoney','Oklahoma','Binding Band');
insert into stores_items(city_name,loc,item_name) values ('Gulf Crest','Texas','Black Sludge');
insert into stores_items(city_name,loc,item_name) values ('Frackville','Pennsylvania','Reset Urge');
insert into stores_items(city_name,loc,item_name) values ('New Chicago','Indiana','Reset Urge');
insert into stores_items(city_name,loc,item_name) values ('Pilsen','Chicago','Start Urge');
insert into stores_items(city_name,loc,item_name)  values ('Lathrup Village','Michigan','Start Urge');
insert into stores_items(city_name,loc,item_name) values ('Lake Wisconsin','Wisconsin','Start Urge');
insert into stores_items(city_name,loc,item_name) values ('Iowa','Iowa','Bright Powder');
insert into stores_items(city_name,loc,item_name) values ('Ipswich','Massachusetts','Bright Powder');
insert into stores_items(city_name,loc,item_name) values ('Quincy','Massachusetts','Cell Battery');
insert into stores_items(city_name,loc,item_name) values ('Railroad','Massachusetts','Cell Battery');
insert into stores_items(city_name,loc,item_name) values ('Rainbow City','Alabama','Choice Band');
insert into stores_items(city_name,loc,item_name) values ('River Rouge','Tennessee','Choice Band');
insert into stores_items(city_name,loc,item_name) values ('Saint Elmo','Illinois','Damp Rock');
insert into stores_items(city_name,loc,item_name) values ('Sofia','Louisiana','Damp Rock');
insert into stores_items(city_name,loc,item_name)  values ('Tampa','Florida','Deep Sea Scale');
insert into stores_items(city_name,loc,item_name) values ('Thunderbolt','Georgia','Deep Sea Scale');
insert into stores_items(city_name,loc,item_name) values ('Topeka','Kansas','Destiny Knot');
insert into stores_items(city_name,loc,item_name) values ('Universal City','California','Destiny Knot');
insert into stores_items(city_name,loc,item_name) values ('Virgin','California','Eject Button');
insert into stores_items(city_name,loc,item_name) values ('Wahoo','California','Mental Herb');
insert into stores_items(city_name,loc,item_name) values ('West Sunbury','Pennsylvania','Mental Herb');
insert into stores_items(city_name,loc,item_name) values ('White Tower','Virginia','Metronome');
insert into stores_items(city_name,loc,item_name)  values ('Y City','Arkansas','Muscle Band');
insert into stores_items(city_name,loc,item_name) values ('Zapata','Texas','Wise Ball');
insert into stores_items(city_name,loc,item_name) values ('Amorita','Oklahoma','Muscle Band');
insert into stores_items(city_name,loc,item_name)  values ('Apache Junction','Arizona','Wise Ball');
insert into stores_items(city_name,loc,item_name) values ('Decatur','Alabama','Sticky Ball');
insert into stores_items(city_name,loc,item_name) values ('Fort Ripley','Minnesota','Safety Goggles');
insert into stores_items(city_name,loc,item_name)  values ('Fountain Hill','Iowa','Safety Goggles');
insert into stores_items(city_name,loc,item_name) values ('Garden Acres','Texas','Sticky Ball');
insert into stores_items(city_name,loc,item_name)  values ('Glenmoor','Maryland','Scope Lens');
insert into stores_items(city_name,loc,item_name) values ('Gran Quivira','New Mexico','Shed Shell');
insert into stores_items(city_name,loc,item_name) values ('Grandfield','Louisiana','Shed Shell');
insert into stores_items(city_name,loc,item_name)  values ('Hamorton','South Carolina','Smoke Ball');
insert into stores_items(city_name,loc,item_name) values ('Jasmine Estates','Florida','Smoke Ball');
insert into stores_items(city_name,loc,item_name) values ('Kachemak City','Alaska','Thick Club');
insert into stores_items(city_name,loc,item_name) values ('Las Animas','Colorado','Thick Club');


insert into stores_items(city_name,loc,item_name) values ('Stony River','Indiana','Binding Band');
insert into stores_items(city_name,loc,item_name)  values ('Sugarloaf','Rio de Janeiro','Float Stone');
insert into stores_items(city_name,loc,item_name) values ('Summit Hill','Dallas','Iron Ball');
insert into stores_items(city_name,loc,item_name)  values ('Sunrise Beach','Missouri','King Rock');
insert into stores_items(city_name,loc,item_name) values ('Waldwick','New Jersey','Iron Ball');
insert into stores_items(city_name,loc,item_name) values ('Abilene','Brooklyn','King Rock');
insert into stores_items(city_name,loc,item_name)  values ('Alamo','New York','Scope Lens');
insert into stores_items(city_name,loc,item_name) values ('Cedartown','Georgia','Smoke Ball');
insert into stores_items(city_name,loc,item_name) values ('Cherry','Alabama','Ability Urge');
insert into stores_items(city_name,loc,item_name) values ('Harrison','Virginia','Master Ball');
insert into stores_items(city_name,loc,item_name)  values ('Keeneland','Kentucky','Heavy Ball');
insert into stores_items(city_name,loc,item_name) values ('Key West','Florida','Moon Ball');
insert into stores_items(city_name,loc,item_name) values ('Kinsey','Texas','Moon Ball');
insert into stores_items(city_name,loc,item_name)  values ('Norbeck','Washington','Love Ball');
insert into stores_items(city_name,loc,item_name) values ('North Albany','New Jersey','Timer Ball');
insert into stores_items(city_name,loc,item_name) values ('Northfork','West Virginia','Timer Ball');
insert into stores_items(city_name,loc,item_name) values ('Oakford','Baltimore','Quick Ball');
insert into stores_items(city_name,loc,item_name) values ('Octavia','San Francisco','Quick Ball');
insert into stores_items(city_name,loc,item_name) values ('Pageland','South Carolina','Lure Ball');
insert into stores_items(city_name,loc,item_name) values ('Palm City','Florida','Lure Ball');
insert into stores_items(city_name,loc,item_name) values ('Panama City','Florida','Net Ball');
insert into stores_items(city_name,loc,item_name) values ('Peabody','Massachusetts','Net Ball');
insert into stores_items(city_name,loc,item_name) values ('Raymond','New Hampshire','Safari Ball');
insert into stores_items(city_name,loc,item_name) values ('Reddick','Illinois','Sport Ball');
insert into stores_items(city_name,loc,item_name) values ('Sanchez','Chicago','Poke Ball');
insert into stores_items(city_name,loc,item_name) values ('Shallow Water','Indiana','Poke Ball');
insert into stores_items(city_name,loc,item_name) values ('Sparta','Tennessee','Poke Ball');
insert into stores_items(city_name,loc,item_name) values ('Tundra','Missouri','Poke Ball');
insert into stores_items(city_name,loc,item_name) values ('Udall','Kansas','Dream Ball');
insert into stores_items(city_name,loc,item_name) values ('Uncasville','Connecticut','Oval Ball');
insert into stores_items(city_name,loc,item_name) values ('Tulalip Bay','Washington','Power Ball');
insert into stores_items(city_name,loc,item_name)  values ('Valley View','Washington','Great Ball');
insert into stores_items(city_name,loc,item_name) values ('Violet Hill','California','Oval Ball');
insert into stores_items(city_name,loc,item_name) values ('Wading River','New York','Great Ball');
insert into stores_items(city_name,loc,item_name)  values ('Waldorf','Maryland','Power Ball');
insert into stores_items(city_name,loc,item_name) values ('West Forks','Arizona','Aurora Ball');
insert into stores_items(city_name,loc,item_name) values ('Yardley','Pennsylvania','Aurora Ball');
insert into stores_items(city_name,loc,item_name) values ('Zelienople','Pennsylvania','Armor Ball');
insert into stores_items(city_name,loc,item_name) values ('Zolfo Springs','Florida','Armor Ball');
insert into stores_items(city_name,loc,item_name) values ('Adel','Georgia','Smoke Ball');
insert into stores_items(city_name,loc,item_name)  values ('Arizona City','Arizona','Smoke Ball');
insert into stores_items(city_name,loc,item_name) values ('Atlantic City','New Jersey','Clever Ball');
insert into stores_items(city_name,loc,item_name) values ('Dime Box','Texas','Clever Ball');
insert into stores_items(city_name,loc,item_name) values ('Dunwoody','Georgia','Explorer Ball');
insert into stores_items(city_name,loc,item_name) values ('Francis Mills','New Jersey','Explorer Ball');
insert into stores_items(city_name,loc,item_name)  values ('Gas City','Indiana','Fire Ball');
insert into stores_items(city_name,loc,item_name) values ('German Valley','Illinois','Fire Ball');
insert into stores_items(city_name,loc,item_name) values ('Hahira','Georgia','Flying Ball');
insert into stores_items(city_name,loc,item_name) values ('Hamilton City','Ohio','Flying Ball');
insert into stores_items(city_name,loc,item_name)  values ('Hendrum','Minnesota','Mind Ball');
insert into stores_items(city_name,loc,item_name)  values ('Imperial Beach','California','Mind Ball');
insert into stores_items(city_name,loc,item_name) values ('Indianapolis','Indiana','Retro Ball');
insert into stores_items(city_name,loc,item_name) values ('Jacksboro','Texas','Fame Ball');
insert into stores_items(city_name,loc,item_name) values ('Kansas City','Kansas','Mind Ball');
insert into stores_items(city_name,loc,item_name) values ('Kettle River','Wyoming','Retro Ball');
insert into stores_items(city_name,loc,item_name) values ('Labouchere Bay','Canada','Fame Ball');
insert into stores_items(city_name,loc,item_name) values ('Ladera Heights','California','Fame Ball');
insert into stores_items(city_name,loc,item_name) values ('Lane City','Oregon','Retro Ball');
insert into stores_items(city_name,loc,item_name)  values ('Las Vegas','Nevada','Lock Ball');
insert into stores_items(city_name,loc,item_name)  values ('Manassas Park','Virginia','Flying Ball');
insert into stores_items(city_name,loc,item_name) values ('Marvell','Arkansas','Focus Ball');
insert into stores_items(city_name,loc,item_name) values ('Milwaukee','Wisconsin','Flying Ball');
insert into stores_items(city_name,loc,item_name) values ('Nelagoney','Oklahoma','Lock Ball');
insert into stores_items(city_name,loc,item_name) values ('Gulf Crest','Texas','Flying Ball');
insert into stores_items(city_name,loc,item_name) values ('Railroad','Massachusetts','Retro Ball');





