insert into cities (city_name) values ('Stony River');
insert into cities (city_name) values ('Sugarloaf');
insert into cities (city_name) values ('Summit Hill');
insert into cities (city_name) values ('Sunrise Beach');
insert into cities (city_name) values ('Waldwick');
insert into cities (city_name) values ('Abilene');
insert into cities (city_name) values ('Alamo');
insert into cities (city_name) values ('Cedartown');
insert into cities (city_name) values ('Cherry');
insert into cities (city_name) values ('Harrison');
insert into cities (city_name) values ('Keeneland');
insert into cities (city_name) values ('Key West');
insert into cities (city_name) values ('Kinsey');
insert into cities (city_name) values ('Norbeck');
insert into cities (city_name) values ('North Albany');
insert into cities (city_name) values ('Northfork');
insert into cities (city_name) values ('Oakford');
insert into cities (city_name) values ('Octavia');
insert into cities (city_name) values ('Pageland');
insert into cities (city_name) values ('Palm City');
insert into cities (city_name) values ('Panama City');
insert into cities (city_name) values ('Peabody');
insert into cities (city_name) values ('Raymond');
insert into cities (city_name) values ('Reddick');
insert into cities (city_name) values ('Sanchez');
insert into cities (city_name) values ('Shallow Water');
insert into cities (city_name) values ('Sparta');
insert into cities (city_name) values ('Tundra');
insert into cities (city_name) values ('Udall');
insert into cities (city_name) values ('Uncasville');
insert into cities (city_name) values ('Tulalip Bay');
insert into cities (city_name) values ('Valley View');
insert into cities (city_name) values ('Violet Hill');
insert into cities (city_name) values ('Wading River');
insert into cities (city_name) values ('Waldorf');
insert into cities (city_name) values ('West Forks');
insert into cities (city_name) values ('Yardley');
insert into cities (city_name) values ('Zelienople');
insert into cities (city_name) values ('Zolfo Springs');
insert into cities (city_name) values ('Adel');
insert into cities (city_name) values ('Arizona City');
insert into cities (city_name) values ('Atlantic City');
insert into cities (city_name) values ('Dime Box');
insert into cities (city_name) values ('Dunwoody');
insert into cities (city_name) values ('Francis Mills');
insert into cities (city_name) values ('Gas City');
insert into cities (city_name) values ('German Valley');
insert into cities (city_name) values ('Hahira');
insert into cities (city_name) values ('Hamilton City');
insert into cities (city_name) values ('Hendrum');
insert into cities (city_name) values ('Imperial Beach');
insert into cities (city_name) values ('Indianapolis');
insert into cities (city_name) values ('Jacksboro');
insert into cities (city_name) values ('Kansas City');
insert into cities (city_name) values ('Kettle River');
insert into cities (city_name) values ('Labouchere Bay');
insert into cities (city_name) values ('Ladera Heights');
insert into cities (city_name) values ('Lane City');
insert into cities (city_name) values ('Las Vegas');
insert into cities (city_name) values ('Manassas Park');
insert into cities (city_name) values ('Marvell');
insert into cities (city_name) values ('Milwaukee');
insert into cities (city_name) values ('Nelagoney');
insert into cities (city_name) values ('Gulf Crest');
insert into cities (city_name) values ('Frackville');
insert into cities (city_name) values ('New Chicago');
insert into cities (city_name) values ('Pilsen');
insert into cities (city_name) values ('Lathrup Village');
insert into cities (city_name) values ('Lake Wisconsin');
insert into cities (city_name) values ('Iowa');
insert into cities (city_name) values ('Ipswich');
insert into cities (city_name) values ('Quincy');
insert into cities (city_name) values ('Railroad');
insert into cities (city_name) values ('Rainbow City');
insert into cities (city_name) values ('River Rouge');
insert into cities (city_name) values ('Saint Elmo');
insert into cities (city_name) values ('Sofia');
insert into cities (city_name) values ('Tampa');
insert into cities (city_name) values ('Thunderbolt');
insert into cities (city_name) values ('Topeka');
insert into cities (city_name) values ('Universal City');
insert into cities (city_name) values ('Virgin');
insert into cities (city_name) values ('Wahoo');
insert into cities (city_name) values ('West Sunbury');
insert into cities (city_name) values ('White Tower');
insert into cities (city_name) values ('Y City');
insert into cities (city_name) values ('Zapata');
insert into cities (city_name) values ('Amorita');
insert into cities (city_name) values ('Apache Junction');
insert into cities (city_name) values ('Decatur');
insert into cities (city_name) values ('Fort Ripley');
insert into cities (city_name) values ('Fountain Hill');
insert into cities (city_name) values ('Garden Acres');
insert into cities (city_name) values ('Glenmoor');
insert into cities (city_name) values ('Gran Quivira');
insert into cities (city_name) values ('Grandfield');
insert into cities (city_name) values ('Hamorton');
insert into cities (city_name) values ('Jasmine Estates');
insert into cities (city_name) values ('Kachemak City');
insert into cities (city_name) values ('Las Animas');
